### PR TITLE
Lower deployment target

### PR DESCRIPTION
**Pull request by rajivshah3**
Lowers iOS deployment target to support older devices

### CODE REVIEW

**Comment by pascalbros** [comment]
It doesn't work in that way, because the code is specific for 64bits archs.
I have a 32bits compatible version, but it seems slower (not that much) on a 64 bit architecture compared to the "master".
I'm planning to put it as a separate branch. Do you need it now?

**Comment by rajivshah3** [comment]
Ah, I didn’t realize there would be a performance difference. Is it possible to reduce it to anything lower than 11? Our app has a deployment target of 8 but I’ll probably raise it because no one uses iOS 8 anymore.

**Comment by dzensik** [comment]
Apple suggests to use 2 last iOS  versions. And this is also my experience with iOS Apps for large user auditoriums. It is enough to support iOS 10 and iOS 11 for now.

**Comment by pascalbros** [comment]
Done, check the 2e7718d commit on develop branch. Minimum deployment target: iOS 8.0 (32 and 64 bits)

**Pull request closed without merging**
